# Generated by Django 4.0 on 2023-08-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Non-Binary'), ('N', 'Prefer not to say')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='likes_dislikes',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
