# Generated by Django 4.2.3 on 2023-07-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='votes',
            field=models.CharField(default='', max_length=200),
        ),
    ]
