# Generated by Django 4.2 on 2023-08-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_alter_tweet_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
