# Generated by Django 4.2 on 2023-08-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweet_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='votes',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
