# Generated by Django 4.0 on 2023-08-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_alter_tweet_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likes_dislikes',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
